//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProject_2.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public string UniversityName { get; set; }
        public string TrainingName { get; set; }
        public string Description { get; set; }
        public string Agno { get; set; }
        public string EducationDate { get; set; }
    }
}
